---
- name: Simple playbook to install and start Apache
  hosts: all
  become: yes   # run tasks with sudo

  tasks:
    - name: Install Apache package
      ansible.builtin.yum:
        name: apache2
        state: present
        update_cache: yes  # update apt cache first

    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Enable Apache to start on boot
      ansible.builtin.service:
        name: apache2
        enabled: yes
