---
- name: Install Apache on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Install nginx 
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
        port: 90

    - name: Write Apache install status to file
      lineinfile:
        path: /tmp/sw_status.txt
        line: "apache2 installed successfully!!"
        create: yes

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and enable Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: install mysql client to node server
      ansible.builtin.apt:
        name: mysql
        state: present

    - name: install phpmyadmin
      ansible.builtin.apt:
        name: phpmyadmin
        state: present

    - name: Create directory
      file:
        path: /tmp/my_directory
        state: directory

    - name: Create file
      command: "touch /tmp/my_directory/my_file.txt"


    - name: Set UFW default policy to allow
      community.general.ufw:
        state: enabled
        policy: allow
        direction: incoming

    - name: Enable UFW
      community.general.ufw:
        state: enabled