apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: stress
    image: progrium/stress
    args: ["--cpu", "2", "--timeout", "300s"]
    resources:
      limits:
        cpu: "1"  # Simulate CPU pressure
        memory: "256Mi"
