# Global Configuration
ServerRoot "/etc/apache2"
PidFile ${APACHE_PID_FILE}
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

# Modules
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Ports
Include ports.conf

# Global Directory Rules
<Directory />
    Options FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

# Log Settings
AccessFileName .htaccess
LogLevel warn
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

# Other configs
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf
