# files/apache2.conf

# Global configuration
ServerRoot "/etc/apache2"
PidFile ${APACHE_PID_FILE}
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

# Logs
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn

# Include the ports configuration
Include ports.conf

# Default site configuration
<Directory />
    Options FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

# Other config includes
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf
